list: $/plus/trc/models/addressmodel/columns.yaml
modelClass: Plus\Trc\Models\AddressModel
title: Address
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
