list: $/plus/trc/models/nodemodel/columns.yaml
modelClass: Plus\Trc\Models\NodeModel
title: Node
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/trc/node/update/:id'
