list: $/plus/trc/models/wdmodel/columns.yaml
modelClass: Plus\Trc\Models\WdModel
title: Wd
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/trc/wd/preview/:id'
