list: $/plus/trc/models/currencymodel/columns.yaml
modelClass: Plus\Trc\Models\CurrencyModel
title: Currency
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/trc/currency/update/:id'
